name: Build and Run OpenAiCodeReview By Main remote Jar
on: #触发器 分支触发名称配置
  push:
    branches:
      - master #推上去的分支
  pull_request:
    branches:
      - master-close #拉取的分支

jobs:
  build:
    runs-on: ubuntu-latest #运行环境

    steps: #执行步骤
      - name: Checkout repository #检出仓库
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 #拉取深度 拉取两条git提交的记录

      - name: Set up JDK 11        # 安装 Java 11 环境
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # 选择 Java 11
          java-version: 11
          
      - name: Check local JAR file
        run: |
          if [ -f "./libs/openai-code-review-sdk-1.0.jar" ]; then
            echo "Using local JAR file"
            ls -lh ./libs/openai-code-review-sdk-1.0.jar
          else
            echo "Error: JAR file not found in ./libs/"
            exit 1
          fi

      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get commit author
        id: commit-author
        run: echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      - name: Get commit message
        id: commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Print repository, branch name, commit author, and commit message
        run: |
          echo "Repository name is ${{ env.REPO_NAME }}"
          echo "Branch name is ${{ env.BRANCH_NAME }}"
          echo "Commit author is ${{ env.COMMIT_AUTHOR }}"
          echo "Commit message is ${{ env.COMMIT_MESSAGE }}"      

      - name: Run Code Review
        run: java -jar ./libs/openai-code-review-sdk-1.0.jar
        env:
          # Github 环境变量配置
          GITHUB_REVIEW_LOG_URI: ${{ secrets.CODE_REVIEW_LOG_URI }} # 日志上传地址
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }} # Github 访问Token
          COMMIT_PROJECT: ${{ env.REPO_NAME }} # 项目名
          COMMIT_BRANCH: ${{ env.BRANCH_NAME }} # 分支名
          COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }} # 提交作者
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }} # 提交信息
          # 微信 环境变量配置 https://open.weixin.qq.com/connect/qrconnect?appid=wx39c379788eb1286a&scope=snsapi_login&redirect_uri=http%3A%2F%2Fmp.weixin.qq.com%2Fdebug%2Fcgi-bin%2Fsandbox%3Ft%3Dsandbox%2Flogin
          WEIXIN_APPID: ${{ secrets.WEIXIN_APPID }} # 微信 APPID
          WEIXIN_SECRET: ${{ secrets.WEIXIN_SECRET }} # 微信 SECRET
          WEIXIN_TOUSER: ${{ secrets.WEIXIN_TOUSER }} # 接收消息的微信用户id
          WEIXIN_TEMPLATE_ID: ${{ secrets.WEIXIN_TEMPLATE_ID }}  # 微信模板id
          # OpenAi - ChatGLM 环境变量配置「https://open.bigmodel.cn/api/paas/v4/chat/completions」、「https://open.bigmodel.cn/usercenter/apikeys」
          CHATGLM_APIHOST: ${{ secrets.CHATGLM_APIHOST }} # ChatGLM APIHOST: https://open.bigmodel.cn/api/paas/v4/chat/completions
          CHATGLM_APIKEYSECRET: ${{ secrets.CHATGLM_APIKEYSECRET }} # ChatGLM APIKEYSECRET: https://open.bigmodel.cn/usercenter/apikeys
